---
title: "SCORE: Fielding-Miller et al. (2020) replication"
subtitle: "Missings"
author: "Radoslaw Panczak"
date: "`r format(Sys.time(), '%d %B, %Y')`"
mainfont: DejaVu Sans
output: 
  html_document: 
    toc: true
    toc_depth: 4
    toc_float: true
    number_sections: true
    theme: united 
    highlight: pygments 
editor_options: 
  chunk_output_type: console
---

<!-- ------------------------------------------------------------ --> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      fig.width=8, fig.height=6, dpi=300, 
                      out.width="800px", out.height="600px")

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(scipen=999)

set.seed(12345)

library(pacman) 

p_load(tidyverse, sf, tmap, scales,
       igraph, spdep)

tmap_mode("view")
```


```{r}
counties <- st_read("data-raw/Raw files/Spatial/cb_2018_us_county_20m/cb_2018_us_county_20m.shp") %>% 
  select(-ALAND, -AWATER) %>% 
  mutate(fips = as.double(GEOID)) %>% 
  filter(STATEFP < 60)

fips_original <- read_csv("data/fips_original.csv")
fips_extended <- read_csv("data/fips_extended.csv")
```


```{r}
counties %>% 
  anti_join(fips_original) %>% 
  qtm(borders = "purple", fill = NULL )#, text= "NAME", text.col = "purple")
```

```{r}
counties %>% 
  anti_join(fips_extended) %>% 
  qtm(borders = "purple", fill = NULL )#, text= "NAME", text.col = "purple")
```

